### PR TITLE
Remove use of Klaviyo API v2, use 2024-05-15 revision instead

### PR DESCRIPTION
**Pull request by lusimeon**
## Description

Klaviyo v2 API is EOL : https://developers.klaviyo.com/en/docs/api_versioning_and_deprecation_policy. This PR updates calls to Klaviyo API to be compatible with new API endpoints.

## Breaking changes
- Remove `spatie/data-transfer-object` package because not maintained and not used.
- Return type of `Setono\SyliusKlaviyoPlugin\Client\RestClientInterface::get()` and `Setono\SyliusKlaviyoPlugin\Client\RestClientInterface::post()` change from `array` to `Symfony\Contracts\HttpClient\ResponseInterface\ResponseInterface`
- Updates on `Setono\SyliusKlaviyoPlugin\DTO\Properties\CustomerProperties` properties:
  - Move `zip`, `city`,  `region`, `country` properties in `Setono\SyliusKlaviyoPlugin\DTO\Properties\Location` class and define a new property `location`.
  - Remove `id` property in favor of `externalId`.
  - Remove `exchangeId` property.
  - Remove `consent` property in favor of `subscriptions` property (Setono\SyliusKlaviyoPlugin\DTO\Properties\Subscriptions).
  - Automatically populate properties for CustomerInterface (see `Setono\SyliusKlaviyoPlugin\DTO\Properties\CustomerProperties::populateFromCustomer()`).
- `setono_sylius_klaviyo.event_subscriber.update_customer_properties_from_order` service constructor require one new service `setono_sylius_klaviyo.dto.properties.factory.properties`.
- `setono_sylius_klaviyo.client.track_identify` service require `setono_sylius_klaviyo.client.rest` service in constructor instead of `http_client` service.
- `setono_sylius_klaviyo.message.handler.subscribe_customer` service require `setono_sylius_klaviyo.dto.properties.factory.properties` and `serializer` in constructor.

close [#69](https://github.com/Setono/SyliusKlaviyoPlugin/issues/69)

### CODE REVIEW

**Comment by JoppeDC** [comment]
This has been on my todo list for ages. You are a legend.

First quick glance it looks good. Maybe check if you can fix the codestyle and the static analysis warnings.

**Comment by lusimeon** [comment]
I've fixed codestyle and i've updated tests to match with new klaviyo's endpoints payload. A maintainer seems to be required to re-run CI checks.

**Comment by lusimeon** [comment]
Hi, any help to fix dependency analysis CI checks?
The `symfony/http-client` package is marked by composer-unused as `unused` but it is really needed. It works locally but not on CI. I tried to ignore it, [without success](https://github.com/Setono/SyliusKlaviyoPlugin/actions/runs/9647796605/job/26616769492?pr=74).

**Comment by loevgaard** [comment]
Hi, @lusimeon 

This is a great PR. Thank you. I will merge it into the branch and work on other improvements in another PR.

**Pull request merged**
